---
author: James  Watmough
date: "`r Sys.Date()`"
---

{{< include texmacros.qmd >}}

# Functions and Models {#sec-functions}

## Functions and variables

Functions arise whenever one quantity (or state) can be *determined* from another.
Functions also arise whenever we *theorize* that one quantity (or state) could be determined from another.

Examples:

- Reducing screen brightness increases Battery life.
- The temperature of tap water depends on the time since the tap was opened.
- The area of a circle depends on its radius.
- The rate a predator encounters prey depends on the size of the prey population.

The quantity being determined is often referred to as the *dependent variable*, and the other quantify is the *independent variable*.   For your first calculus course, almost all the example functions will have a single output and a single input, but in practice, we usually have several inputs and several outputs.  We don't usually view all the inputs as *variable*.  The most common names for the inputs that we're not varying are parameters, constants, or coefficients. 

Note our quantities are only labeled as variables or parameters for a specific question.  For example, our tap-water temperature probably also depends the temperature of the hot water tank and the outdoor temperature.  We might view these as fixed, but we might also be interested in knowing what happens as the outdoor temperature changes.  We may also want to flip the question around and ask how long the water needs to run to reach a certain temperature.  Now the time is the dependent variable, and the water temperature is the independent variable.  

::: {#def-function}

# Function

A function consists of two sets, $A$ and $B$, together with a rule that assigns exactly one element of $B$ to each 
and every element of $A$.

:::

It is common to think of the elements of $A$ as *inputs*.  The function matches each and every input in $A$ to exactly one *output* from $B$.

- Ideally a function should be given a clear descriptive name, but it is often denoted by a single letter, like $f$.
- The set $A$ in @def-function is referred to as the *domain* of $f$.
- The set $B$ is referred to as the *codomain* of $f$.
- We say $f$ is a function from $A$ into $B$, and sometimes write $f:A\rightarrow B$.  
- We use $f(x)$ to denote the element of $B$ assigned to an element $x$ of $A$ by $f$.
- The *range* of $f$ is the set $\set{y\in B}{y=f(x), x\in A}$.

When we are using variables and functions to explain concepts it is a good
idea to name the variables and functions in meaningful ways.  For example,
suppose we need a function to model the rate a lioness searches for prey.
When the number of prey is low,  she will chase down every prey she sees, but
when there are lots of prey available, she will only chase down enough to
satisfy her hunger.  A simple model for this saturation effect is a hyperbola.
We could use a descriptive name like
$\texttt{Prey}$ to denote the number of prey, our independent variable.  $\texttt{Prey}$ should be a positive real number.  Then we could give our function a descriptive name like $\texttt{Lioness\_Attack}$ and define it by the rule 
\begin{equation}
  \texttt{Lioness\_Attack}(\texttt{Prey}) = \frac{\texttt{attack\_rate}\times\texttt{Prey} }{ \texttt{saturation\_level} + \texttt{Prey} }, \qquad \texttt{Prey} \ge 0.
\end{equation}

Here `attack_rate` and `saturation_level` are parameters, 
`Prey` is the independent variable, and
`Lioness_Attack` is the function.   

While descriptive variable and function names are helpful at times, they can be annoying at times, especially if we are trying to solve equations algebraically.  In most math courses, variable and function names will be denoted by single letters.

Another common way to specify a function is using a arrow with the input on one side and the output on the other.  For example
$$x\mapsto x^2 + 2, x \in \R$$
defines a function whose input is any real number and whose output is two plus the square of the input.  Notice how this lets us define a function without the complication of naming it.   In many programming languages this is referred to as an *anonymous* function.    

::: {#exm-function-1}
# Function Notation
Let $P$ be the function defined by 
$$x \mapsto 3x^2 - x + 5, \quad x\in \R.$$
Think of $P$ as the name of the function, and $P(x)$ as the value of the function at $x$.

- the value of $P$ at 2 is $$P(2) = 3(2)^2 - (2) + 5 = 12 - 2 + 5 = 15$$
- given a number, $t$, the value of $P$ at $t+1$ is $$P(t+1) = 3 (t+1)^2 - (t+1) + 5$$
- given a number, $x$, the value of $P$ at $x^2$ is $$P(x^2) = 3 (x^2)^2 - (x^2) + 5$$
:::

This notation lets us define new functions using previously named functions. For example, $g$ can be defined by the rule $g(x) = P(x^2)$.

::: {#def-images}
  Given a function, $f$, the *image* of a subset $U$ of the domain of $f$, denoted simply by $f(U)$, is the set of all outputs reached by inputs in $U$.  That is, $$f(U) = \set{y\in B }{ y=f(x), x\in U}.$$    The *preimage* or *inverse image* of a subset $V$ of the codomain of $f$, denoted by $f^{-1}(V)$, is the set of all inputs whose corresponding outputs are in $V$.  That is, $$f^{-1}(V) = \set{x\in A}{\text{$y=f(x)$ for some $y \in V$}}.$$
:::


