---
author: James  Watmough
date: "`r Sys.Date()`"
---

{{< include texmacros.qmd >}}

# Numbers, Sets, and Sequences {#sec-sequences}

Two good, simple, open-source introductions to sets are the Wiki-Books on Set Theory\footnote{\url{http://en.wikibooks.org/wiki/Discrete_mathematics/Set_theory}} and Abstract Algebra\footnote{\url{http://en.wikibooks.org/wiki/Abstract_Algebra/Sets}}.  These give the basic ideas and notation along with a few simple exercises that should suffice for a review.   The first chapter of Lax and Terrell [-@lax2020calculus] gives an good introduction to sets and sequences. For the purpose of the current notes we will limit ourselves to a brief discussion of the main notation needed for the basics of calculus, analysis and linear algebra. 

A set is a well-defined collection of objects.  The key here is that sets are *well-defined*.  We must be able to decided unambiguously if a given object is a member of a set or not.   If the object $x$ is in the set $S$, we say $x$ is an element of $S$ and write $x\in S$.  If $x$ is not an element of $S$ we write $x\not\in S$.  By well-defined, we mean that these are the only two possibilities.  Given an object and a set, either the object is in the set or it isn't.  There can be no ambiguity. We will typically denote sets by capital letters and elements of sets by lowercase letters.   

## Sets

A set is typically defined by specifying its elements, either as a list or through properties.  We'll use $\N$, $\Z$, $\Q$ and $\R$ to denote the counting numbers, integers, rationals and real numbers respectively.  The notation $\set{x\in \Z}{x^2>10}$ should be read as the set of integers, $x$, such that $x^2>10$, or more simply, the set of all integers whose square is larger than 10.   The order we list the elements of a set doesn't matter, nor does repetition.  The sets $\{5,10\}$ and $\{10,5\}$ and $\{10,5,5\}$ are the same.  They each have two elements, 10 and 5.  If the order of elements is important, we will use ordered pairs, ordered tuples, or sequences and denote them using parentheses (round brackets) instead of braces (curly brackets).  Thus $(5,10)$ and $(10,5)$ are different ordered pairs, $(10,5,5)$ is an ordered triple and $(2,4,6,8,\dots)$ is the sequence of even counting numbers.

There are a number of definitions that will prove useful.
::: {#def-subset}
Let $A$ and $B$ be sets.
- $A$ is a subset of $B$, written $A\subseteq B$ or $B\supseteq A$, if every element of $A$ is an element of $B$.
- Two sets are equal, written $A=B$ if, $A\subseteq B$ and $B\subseteq A$.
- $A$ is a proper subset of $B$, written $A\subset B$ or $B\supset A$, if every element of $A$ is an element of $B$ and $A\ne B$.
- The empty set, denoted $\emptyset$, is the set with no elements.  It is a subset of every set.
- The union and intersection of $A$ and $B$ are the sets 
  \begin{align*}
    A\cup B &= \set{s}{\text{$s$ is an element of either $A$ or $B$ or both $A$ and $B$}} \\
    A\cap B &= \set{ s }{ \text{$s$ is an element of both $A$ and $B$} }
  \end{align*}
:::

## Length and number

Perhaps a good place to start an introduction to calculus is with the distinction between the numbers and the rational numbers.
A good working definition of the real numbers is the set of all possible differences in lengths
Throughout these notes, we'll use $\N$ to denote the counting numbers, $\Z$ to denote the integers, $\Q$ to denote the rationals, and $\R$ to denote the reals.   Thus,
\begin{align*}
  \N &= \left\{1,2,3,\dots\right\},\\
  \Z &= \left\{\dots,-3,-2,-1,0,1,2,3,\dots\right\},\\
  \Q &= \left\{\text{all fractions $\dfrac{p}{q}$, where $p$ and $q$ are integers, $q\ne0$}\right\}.
\end{align*}

:::{.callout-note}
There are several ways to rigorously define the real numbers. A reasonable discussion can be found at \url{http://en.wikipedia.org/wiki/Construction_of_the_real_numbers}.  
:::

The counting numbers are used for enumerating things.  The integers arise naturally when we need to take differences of counting numbers.  The rational numbers arise when we need to divide, or take ratios of the natural numbers.  

It came as a bit of a shock to the ancient greeks to discover that not all numbers were rational
\url{http://www.math.ufl.edu/~rcrew/texts/pythagoras.html}, or more precisely, that there were lengths
that could not be expressed as a ratio of two counting numbers.  The proof of this is quite accessible with the basics of logic and an understanding of factors
\url{http://www.homeschoolmath.net/teaching/proof_square_root_2_irrational.php}.
However, our introduction starts not with the existence of irrational numbers, but the question of how to construct the real numbers.   In what follows, we leave off the adjective *real*, so all numbers can be assumed to be real numbers unless stated otherwise.

\subsection{The Set of Real Numbers}

The real numbers are an **ordered set**:  for every pair $(a,b)$, either $a < b$, $a=b$ or $a>b$.   
This ordering allows us to talk about bounds on sets.  This concept is useful later on.  Of course the counting numbers, integers and rationals are also ordered.  In this next definition, we are mainly interested in the case where $X$ replaced by $\R$.

::: {#def-bounded-set}

# bounded sets

Suppose $X$ is an ordered set and $S$ is a non-empty subset of $X$.
- We say $S$ is *bounded above* if there is an element $u$ of $X$ such that $a\le u$ for every $a\in S$.  
- We say $S$ is *bounded below* if there is an element $l$ of $X$ such that $a\ge l$ for every $a\in S$.  
- A set is *bounded* if it is both bounded above and bounded below.
- A set is *unbounded* if it isn't bounded.
:::

Note that the bounds $u$ and $l$ in the above definitions need not be an element of $S$.    We refer to $u$ as an upper bound for $S$ in $X$ and $l$ as a lower bound for $S$ in $X$.  More often than not, the set $X$ is assumed to be `obvious' and is not explictly stated!    In our case, it's probably safe to assume $X$ is the real numbers.

::: {#def-extrema}

# maximum and minimum

Suppose $X$ is an ordered set and $S$ is a non-empty subset of $X$.
- If $S$ contains a largest element $s$, then we call $s$ the maximum of $S$ and write $s = \max S$.
- If $S$ contains a smallest element $s$, then we call $s$ the minimum of $S$ and write $s = \min S$.
:::

The maximum and minimum values, if they exist, are elements of $S$.    A set can be bounded but not have a minimum or maximum value.  For example, the set $(0,1)$ of all (real) numbers between 0 and 1 has 0 and 1 as lower and upper bounds, but it does not have maximum or minimum values.
The maximum and minimum values of $S$, if they exist, are also bounds on $S$.  However, a bound need not be a maximum or minimum.

::: {.callout-warning}
Note that $(0,1)$ is used to denote the open interval $\set{x\in\R}{0 < x < 1}$ as well as the ordered pair.  The intended meaning should always be clear from the sentence structure or argument in which the notation is used.  Remember to take care using mathematical notation:  it should be used to clarify, not obfuscate.
:::

There are many cases where it will be sufficient to know that a set is bounded.  For this,  any bound will do.  However, we are often interested in finding the least upper bound or greatest lower bound.    For this we need another definition.

::: {#def-inf-sup}

# infimum and supremum

Suppose $X$ is an ordered set and $S$ is a non-empty subset of $X$.
- An element $u$ of $X$ is a least upper bound for $S$ if $u$ is an upper bound for $S$ and $u \le M$ for every upper bound $M$ of $S$.
- An element $l$ of $X$ is a greatest lower bound for $S$ if $l$ is a lower bound for $S$ and $l \ge M$ for every lower bound $M$ of $S$.
:::

It is left as an exercise to show that the least upper bound of a set $S$, if one exists, is unique. We sometimes refer to this bound as the supremum of $S$ and denote it by $\sup S$.  The lower bound of $S$, if it exists, is also unique and is referred to as the infimum of $S$, or $\inf S$.   

For example,  take $X$ as the rational numbers and let $S$ be the set $S = \set{ s \in \Q }{ s = 1 + 1/n, n\in \N}$.  Any  rational number 2 or larger is an upper bound for $S$ and any number 1 or lower as a lower bound.  The maximum of $S$ is 2, but $S$ has no minimum.  Given any number $a>1$, there will be some counting number $N$ for which $ 1 + 1/N < a$.  Hence no lower bound for $S$ is larger than 1.  As defined below,  1 is the greatest lower bound of $S$.  

If $S$ has a maximum, then the maximum is also the supremum of $S$.    However, the reverse is not always true.
For example,  the interval $(0,1)$ consisting of all rational numbers between $0$ and $1$ is bounded.    The infimum and supremum are $0$ and $1$ respectively, but the set has no maximum or minimum.   The set $[0,1]$ of all rational numbers between $0$ and $1$ inclusive has both maximum and minimum values.   More interestingly,  the set of all rational numbers whose square is less than 2 is bounded, but has no least upper bound in the rational numbers.    

Defining the real numbers as lengths is a good starting point.  However, to proceed with analysis we need to understand the properties of the real numbers.  One approach, which is too time-consuming for our purposes, would be to rigorously define the real numbers and deduce their properties from these definitions.  We will take the opposite approach and state the desired properties as axioms.  Thus, the real numbers are an ordered field[^field],
they contain the rational numbers as a subset, and they satisfy the following axiom.

::: {.callout-note icon=false appearance="simple"}

# Axiom of Completeness

Every subset of $\R$ that is bounded above has a least upper bound.
:::

In short,  $\R$ is the set of rational numbers with all the holes filled in.   

[^field]: The real numbers are an example of an algebraic structure known as a field:  $\R$ is closed under addition and multiplication, it contains the additive and multiplicative identities, 0 and 1, and every element of $\R$ except 0 has both an additive and a multiplicative inverse.}

It is interesting to note that the axiom of completeness implies an axiom of Archimedes that we will use frequently.

::: {#thm-archimede} 

# Archimede's Principle

  If $a$ and $b$ are positive numbers, then there is a natural number $n$ for which $na > b$.
:::

::: {.proof}
Suppose that there is no such number and let $S$ be the set of all numbers less than $na$ for some natural number $n$.   Since we're supposing Archimedes Principle doesn't hold, $b$ is an upper bound for $S$.  By the Axiom of Completeness, $S$ must have a least upper bound, call it $s$.  Since $s$ is the least upper bound for $S$, $s-a$ must be less than $na$ for some $n$, but then, $s-a < na$ implies $s < (n+1)a$.  Since $(n+1)a$ is an element of $S$, $s$ could not be an upper bound for $S$, contradicting the completeness axiom.  Our supposition that $S$ is bounded above must be false and Archimede's Principle must hold.
:::

Of course, Archimede's Principle also holds for rational numbers, for which the completeness axiom does not hold.  

A familiar variation of Archimede's Principle is obtained by setting $b$ equal to one.
::: {#cor-archimede}
  If $a$ is a positive number, then there is a natural number $n$ for which $0 < 1/n  < a$.
:::

## Sequences

### Sequences of Real Numbers

A **sequence** is a set whose elements are indexed by the natural numbers.
We write sequences as $a_0, a_1, a_2, \dots$, or $(a_n)$.   Sometimes the index set is explicit in the notation as $(a_n)_{n=0}^\infty$.   

::: {#def-seq-prop}
There are several important terms to know:

a. a sequence is *increasing* if $a_n>a_m$ whenever $n>m$;
a. a sequence is *decreasing* if $a_n<a_m$ whenever $n>m$;
a. a sequence is *non-increasing* if $a_n\le a_m$ whenever $n>m$;
a. a sequence is *non-decreasing* if $a_n\ge a_m$ whenever $n>m$;
a. a sequence is *monotone* if it is one of the above;
a. a sequence is *bounded above* if there is a real number $M$ such that $a_n\le M$ for every index $n$;
a. a sequence is *bounded below* if there is a real number $M$ such that $a_n\ge M$ for every index $n$;
a. a sequence is *bounded* if it is **both** bounded above and bounded below;
a. a sequence is *unbounded* if it isn't bounded;
a. given a set $S$, we say a sequence $(a_n)$ is a sequence in $S$ if each $a_n$ is a point in $S$.

:::

::: {#def-convergence} 

# convergence of sequences

A sequence of real numbers is said to *converge* to a real number $L$ if for each $\epsilon > 0$, there is a number $N$ such that $|a_n-L| < \epsilon$ for every index $n>N$.    We write $a_n\rightarrow L$, or $\lim a_n=L$, and refer to $L$ as the *limit* of the sequence.
:::

Geometrically, we can view these statements as requiring that eventually (i.e., for $n>N$) all the terms of the sequence stay within a distance $\epsilon$ of $L$.  Since $\epsilon$ is an arbitrary positive number, the tail of the sequence stays arbitrarily close to the limit $L$.
Another way to state this definition would be to say that  a sequence converges to $L$ if there is a function $N$ such that for each number $\epsilon>0$, $n > N(\epsilon) \rightarrow |a_n-L| < \epsilon$.  With this wording, proving that a sequence converges can be done by solving the inequality for $n$. 

::: {#exm-seq-1}
The sequence $(a_n)$ defined by $a_n=1/n$ converges to zero.   To show this is true, start with any real number $\epsilon > 0$,  and rewrite the inequality $\abs{\frac{1}{n}-0} < \epsilon$ in the form  $n > \frac{1}{\epsilon}$.   In a sense, we are rewriting our demand that terms in the sequence stay within a distance $\epsilon$ of the limit, as a condition that $n$ must satisfy to meet this demanded *tolerence*.   
:::

::: {#exm-seq-2}
Show that the following sequences converge and find the limit:  
1. $\frac{2}{n}$,
1. $\frac{1}{n^2}$,
1. $\frac{1 - (1/2)^n}{1 - 1/2}$,
1. $\frac{1+3n}{3+n}$.

At this point, the only approach we can use is to guess at the limit and then try to solve the inequality $a_n-L<\epsilon$ for $n$.
In guessing at the limit, you will intuitively make use of some rules for limits we'll prove later on.  

1. Since each term is clearly positive and become arbitrarily small as $n$ increases, we guess the limit is zero.   We set $L=0$ in the definition and try to solve for $n$:
 $$\left| \frac{2}{n} - 0 \right| < \epsilon \Leftrightarrow 2/n < \epsilon \Rightarrow  n > 2/\epsilon.$$
 Note that when we play with the inequality, it is safe to assume $n>0$ and $\epsilon>0$.
  
1. We guess the limit is zero for the same reason:
  $$\left| \frac{1}{n^2} - 0 \right| < \epsilon \Leftrightarrow 1/n^2 < \epsilon \Rightarrow  n > 2/\epsilon.$$

1. Since $(1/2)^n$ approaches zero as $n$ increases, we make a guess by replacing $(1/2)^n$ by zero, which suggests a limit of $L=2$.  To solve the inequality, first simplify $|a_n-L|$:
$$\left| \frac{1 - (1/2)^n}{1 - 1/2} - 2 \right|  
		  = \left|  - (1/2)^{n-1} \right|  
		  = 1/2^{n-1}$$
Hence, $\left| \frac{1 - (1/2)^n}{1 - 1/2} - 2 \right|  < \epsilon  
\Leftrightarrow  1/2^{n-1} < \epsilon  
\Leftrightarrow  n  > 1-\log_2\epsilon$

Note that if $\epsilon > 2$, then the right hand side is negative, implying any positive $n$ works.  The right hand side is positive for smaller $\epsilon$, which is what we are interested in for convergence of sequences.
1. If we divide the numerator and denominator by $n$ and then replace $1/n$ and $3/n$ by zero, we guess the limit is $3$.  To see if this is correct, we try to solve the resulting inequality for $n$.  First, simplify $|a_n-L|$
$$\left| \frac{1+3n}{3+n} - 3 \right| 
	  = \left|  \frac{(1+3n) - 3(3+n)}{3+n} \right|  
	  = \left|  \frac{-8}{3+n} \right|  
	  = 8/(3+n)  $$
Hence, $\left| \frac{1+3n}{3+n} - 3 \right|  < \epsilon 
	 \Leftrightarrow 8/(3+n) < \epsilon 
	 \Leftrightarrow n > (8/\epsilon) - 3$

:::

::: {#thm-seq-lim-unique}
If a sequence $(a_n)$ converges then the limit is unique.
:::

::: {.proof}
Suppose $(a_n)$ converges with $\lim a_n = L$.   Let $M$ be any real number distinct from $L$, and choose $\epsilon = |L-M|/2$.  For some $N$ we have that for all $n>N$, $a_n$ is in the interval $(L-\epsilon, L+\epsilon)$, which, by our choice of $\epsilon$, has no points in common with the interval $(M-\epsilon, M+\epsilon)$. Hence, $(a_n)$ does not converge to $M$, and $L$ is the unique limit.
:::

:::{#thm-seq-sum}
If $(a_n)$ and $(b_n)$ converge with limits $L$ and $M$ respectively,  then the sequence $(c_n)$ defined by $c_n = a_n+b_n$ converges with limit $L+M$. 
:::

::: {.proof}
Given a real number $\epsilon>0$,  there is a number $N$ so that $|a_n-L| < \epsilon/2$, and $|b_n - M|<\epsilon/2$.  Since $|x+y| \le |x|+|y|$ for any pair,  $x$ and $y$, of real numbers.  It follows that for $n>N$
$$|c_n-(L+M)| = |a_n + b_n - (L + M)| \le |a_n-L|+|b_n-M| < \epsilon.$$
:::

::: {#exr-seq-prod}
Show that if $(a_n)$ and $(b_n)$ converge with limits $L$ and $M$ respectively,  and $c$ is a real number, then the sequences $(-a_n)$, $(a_n-b_n)$, $(ca_n)$, $(a_nb_n)$  and $(a_n/b_n)$  defined in the obvious way all converge with limits $-L$, $L-M$, $cL$, $LM$  and $L/M$ respectively.    Note for the last case you must assume that $b_n\ne0$ and $M\ne0$.  
:::

There are two useful inequalities that help with the examination of the product of two sequences.  First, we can expand the difference $|a_nb_n-ab|$ as $|a_nb_n-a_nb+a_nb-ab|$.   So by the triangle inequality we know 
$$|a_nb_n-ab| = |a_nb_n-a_nb+a_nb-ab| < |a_nb_n-a_nb|+|a_nb-ab| = |a_n||b_n-b|+|a_n-a||b|.$$   
Second,  if $|a_n-a| < \epsilon$ and $\epsilon>0$, then it is also true that $|a_n| < |a|+\epsilon$.  


::: {#thm-squeeze}

# The squeeze theorem

If $(a_n)$ and $(b_n)$ are two convergent sequences with $\lim a_n = L$ and $\lim b_n = M$, and if there is a third sequence $(c_n)$ with $a_n < c_n < b_n$, then $(c_n)$ converges with $L \le \lim c_n \le M$.  
:::

::: {#thm-seq-mono-bounded}
All bounded monotone sequences converge.
:::

::: {.proof}
It is sufficient to prove the case where the sequence is nondecreasing.  
Suppose that $(a_n)$ is nondecreasing and bounded above.  Since $(a_n)$ is bounded, the sequence has a least upper bound.  Call this $L$.  It seems reasonable to suppose that $a_n\rightarrow L$.  To prove it does, simply let $\epsilon$ be any positive number.  Either there is some number $N$ for which $L-\epsilon < a_N$, or $a_n \le L-\epsilon$ for all $n$.  The second case implies that $L-\epsilon$ is an upper bound for $(a_n)$, contradicting our declaration of $L$ as the least upper bound, so we know the first case must be true.  Since $L$ is a least upper bound and $(a_n)$ is nondecreasing, it must be that $L-\epsilon < a_n \le L$ for all larger $n$ as well. Which in turn implies $|a_n-L|<\epsilon$ for all $n > N$.  
:::

It is important to see how we used the least upper bound axiom to prove this monotone convergence theorem.  This is the first step in a chain of theorems following from the least upper bound axiom.

::: {#thm-nested-interval}
Suppose that $I_n$ is a closed interval for each natural number $n$, and suppose that $I_{n+1} \subset I_n$.  Then $\cap_{n=1}^\infty I_n$ contains at least one element.  Further, if the widths of the intervals tends to zero, then $\cap_{n=1}^\infty I_n$ contains exactly one element.
:::

::: {.proof}
This follows fairly directly from the monotone convergence theorem.  First, let $a_n$ and $b_n$ be the left and right enpoints of $I_n$, respectively.  The nesting of the sets implies $(a_n)$ is nondecreasing and $(b_n)$ is nonincreasing.  Hence, both sequences have limits, which we'll call $a$ and $b$.  If $a<b$, then $\cap_{n=1}^\infty = [a,b]$.  This is possibly more subtle than you might have realized.  We need to show two things:  first, that if $x$ is a number in the interval $[a,b]$, then $x$ is a member of every subset $I_n$, and second, that if either $x<a$ or $x>b$, then $x$ isn't a member of at least one of the sets.  The first follows since $a_n \le x \le b_n$ for each $n$.  To show the second, if $x<a$ then there must be some $n$ for which $x < a_n \le a$, since $a$ is the least upper bound for $(a_n)$.  The last case, $x > b$ is similar.  Finally,  it must be that if $a=b$, then the width of the intervals decreases to zero, but since each interval is closed, the common limit is a member of $I_n$ for every $n$.
:::

::: {#def-cauchy-seq}
A sequence $(a_n)$ is said to be **Cauchy** if for every positive number $\epsilon$ there is a number $N$ depending on $\epsilon$ so that 
  $$n>N(\epsilon) \Rightarrow |a_n-a_m| < \epsilon.$$
:::

::: {#thm-cauchy-seq}
Every Cauchy sequence converges
:::

::: {.proof}
Let $(a_n)$ be Cauchy.  Pick any positive number and call it $\epsilon_1$.  Since $(a_n)$ is Cauchy we know that there is a number $N_1$ guaranteeing $|a_n-a_m|<\epsilon_1$ whenever both  $n$ and $m$ are larger than $N_1$.  Pick any number $n_1$ and let $I_1 = [a_{n_1}-\epsilon_1, a_{n_1} + \epsilon_1]$.  Notice that $a_n \in I_1$ for all $n>N_1$.  Now pick a second positive number $\epsilon_2 < \epsilon_1$.  Again, we know that there is a number $N_2 > N_1$ guaranteeing $|a_n-a_m| < \epsilon_2$ whenever both $n$ and $m$ are larger than $N_2$.  Now pick any $n_2 > N_2$.  Notice that  for $n > N_2$, $a_{n_2} -\epsilon_2 < a_n < a_{n_2} +\epsilon_2$.  We can't be certain that this second interval is nested withing the first, but since $N_2$ was chosen to be larger than $N_1$, it follows that $a_n$ is also in $I_1$.   Hence, 
$$n > N_2 \Rightarrow a_n \in I_2 = I_1\cap [a_{n_2}-\epsilon_2, a_{n_2} + \epsilon_2].$$
Continuing in this fashion we see that we can construct a sequence of nested closed intervals each containing some tail of our Cauchy sequence.  Since each $\epsilon_k$ is arbitrary, we can ensure the width of the intervals tends to zero.  By the Nested Interval Theorem,  their intersection contains exactly one number, call it $L$.  Finally,  given any positive number $\epsilon$, there is some number $N$ for which the width of $I_N$ is less than $\epsilon$,  implying $|a_n-L| < \epsilon$ for every $n$ larger than $N$.   The sequence converges to the limit $L$.
:::

We have now constructed a chain of theorems starting from our Least Upper Bound Axiom.  It is worth taking some time to explore how tightly connected these statements are.  As an exercise, begin instead with the axiom that all Cauchy sequences converge and from that deduce that every bounded set has a least upper bound.  Since decimal expansions for numbers can be viewed as Cauchy sequences, this is similar to starting with the axiom that all real numbers can be expressed as decimal numbers.  Having connected the four statements in a loop, we see that any one of them can be taken as a axiom on which to construct the real numbers.

### Subsequences

::: {#def-subsequence}
A **subsequence** of a sequence $(a_n)$ is any sequence $(a_{n_k})$ where $(n_k)$ is an increasing sequence of natural numbers.  
:::

::: {#thm-mono-subsequence}
Every sequence has a monotonic subsequence.
:::

::: {#thm-bolz-weier}

# Bolzano-Weierstrass

Every bounded sequence has a convergent subsequence.
:::


## Open and Closed Sets

The notion of open and closed sets are connected to limits of sequences and both are central to the ideas of calculus.  Having defined limits of sequences, it is useful to refine our notion of open and closed sets. 


::: {#def-neighbourhood}
By a **neighbourhood** of a point $a$ we mean a set of all points in an open interval containing $a$ except the point $a$ itself.   For example,   the set $B_r = \{x\in \R \| 0 < |x-a| < r \},$ where $r$ is an arbitrary  real number, is a neighbourhood of $a$ often referred to as a ball of radius $r$.
:::

::: {#def-limit-point}
A point $a$ is a **limit point** of a set $S$ if there is a sequence $(a_n)$ in $S$ converging to $a$.
:::

::: {#def-closed-set}
A set of real numbers is said to be **closed** if it contains all its limit points.
:::
